### ISSUE TITLE
Change Requests To Axios

### ISSUE THREAD

**Issue by dephraiim** [Saurabh3333/give-me-a-joke#10]
Requests is deprecated and as it is working now, It may not in the near future.
I think changing the major underlining requests library from request to axios is better.

**Comment by Saurabh3333** [comment]
Would you like to contribute to it?

**Comment by dephraiim** [comment]
Sure, Axios uses promises and that makes it a bit complicated. I have cloned it and I am trying it out. I will get to you for review after.

**Comment by dephraiim** [comment]
I have opened the request. I am waiting for your review

**Comment by Saurabh3333** [comment]
Merged. 
Thank you for your contribution. 
Let me know if you want to enhance this module in any way.
