### ISSUE TITLE
Unable to fetch jokes

### ISSUE THREAD

**Issue by Abhisin90** [Saurabh3333/give-me-a-joke#20]
Inside index.js i have written this code

const jokes = require('give-me-a-joke')
console.dir(jokes)
jokes.getRandomDadJoke((joke) => {
    console.log(joke)
})

On running it 

I am getting this output

![index js - node - Visual Studio Code 30-10-2022 13_15_01 (3)](https://user-images.githubusercontent.com/76687130/198868082-faa18bcc-75e0-4880-ab02-47a9786a5483.png)

Similarly on running 

const jokes = require('give-me-a-joke')
console.dir(jokes)
jokes.getRandomCNJoke((joke) => {
    console.log(joke)
})

my output comes this

![index js - node - Visual Studio Code 30-10-2022 13_18_30](https://user-images.githubusercontent.com/76687130/198868121-0f3d0211-d635-4d44-859d-2a8ad6929510.png)

Is there any problem from my end or yours.
Kindly help.
Thanks for the help in advance

**Comment by user2695** [comment]
Hello @Abhisin90 
The issue is not with the npm package but with the [site](http://api.icndb.com) it gets jokes from. You can verify it by having a look at the source code. As of **Nov 4 2022**, the site is down. 

```
var giveMeAJoke = require("give-me-a-joke");

giveMeAJoke.getRandomDadJoke(function (joke) {
  console.log(joke);
});
```
The above code will work fine because it gets jokes from some other [site](https://icanhazdadjoke.com)

**Comment by walidChaybi** [comment]
it's just of the website is down not because of the pckage, if you try with Dadjokes it works fine, but with CNjokes it doesn't work

**Comment by Saurabh3333** [comment]
Do you guys want to contribute to make this package better? :-)

**Comment by Villian79** [comment]
Hello @Saurabh3333.
To fix `getRandomCNJoke` may I suggest using this [API ](https://api.chucknorris.io/)?
The old [API resource](http://api.icndb.com/) is not available anymore. If it's ok, I will submit a pull request

**Comment by Saurabh3333** [comment]
Go ahead.


Thank you, Regards
Saurabh Shubham
+91-9973286609
***@***.***
