### ISSUE TITLE
I installed this package and my node app is not at all working!

### ISSUE THREAD

**Issue by Aditya-ds-1806** [Saurabh3333/give-me-a-joke#3]
I installed this package and I saw 2 deprecation warnings in the console (related to bodyParser). And then my perfectly functional express app never ran thereafter. I'm having trouble running my other nodejs apps also. None of them seem to work.

**Comment by Saurabh3333** [comment]
@Aditya-ds-1806 I have released a new version of this module and everything is working fine now. Please have a look. Please let me know if you are facing any problem.
