### ISSUE TITLE
Please Update the code.

### ISSUE THREAD

**Issue by Zaid-maker** [Saurabh3333/give-me-a-joke#5]
Hello!
I have used this package for first time and i start discover that it have so many issues. as of you know the request module you use is deprecated and body-parser also have changed. i want to let you know that there is error in line no. 6. here we have to use body-parser middlewares urlencoded. so if you please update this package that's very good.

**Comment by Saurabh3333** [comment]
Hey,
Thank you for the comment. Why don't you consider contributing to it? It would be great.

**Comment by Zaid-maker** [comment]
How?

**Comment by Zaid-maker** [comment]
Please explain me through

**Comment by Saurabh3333** [comment]
Folk this project, then fix it. After all these things, create a pull request with all the details. Finally, I will review it and merge it into the master.

**Comment by Zaid-maker** [comment]
Ok thank you

**Comment by Zaid-maker** [comment]
@Saurabh3333  I have did it go ahead and accept it
